# Generated by Django 4.1.10 on 2023-08-15 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mong', '0003_alter_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
    ]
